from enum import Enum


class SimulationTypes(Enum):
    JUKES_CANTOR = 'Jukes Cantor'
    NAIVE_GILLESPIE = 'naive Gillespie'
    EFFICIENT_GILLESPIE = 'efficient Gillespie'
    BLOCK_LIST = 'block_list'


class EventSubTypes(Enum):
    INSERTION_AT_START = 0
    INSERTION_INSIDE_COPIED = 1
    INSERTION_INSIDE_INSERTED = 2
    INSERTION_AT_END = 3
    DELETION_INSIDE_COPIED_CONTAINED = 4
    DELETION_INSIDE_COPIED_UNCONTAINED = 5
    DELETION_OF_COPIED = 6
    DELETION_INSIDE_INSERTED_CONTAINED = 7
    DELETION_INSIDE_INSERTED_UNCONTAINED = 8
    DELETION_OF_INSERTED = 9
    OUT_OF_SEQUENCE = 10


