from enum import Enum


class SimulationTypes(Enum):
    NAIVE = 0,
    BLOCK_LIST = 1,
    BLOCK_TREE = 2,


class EventSubTypes(Enum):
    INSERTION_AT_START = 0
    INSERTION_AT_START_ADDITION = 1
    INSERTION_INSIDE_COPIED = 2
    INSERTION_INSIDE_INSERTED = 3
    INSERTION_AT_END = 4
    DELETION_INSIDE_COPIED_CONTAINED = 5
    DELETION_INSIDE_COPIED_UNCONTAINED = 6
    DELETION_OF_COPIED = 7
    DELETION_INSIDE_INSERTED_CONTAINED = 8
    DELETION_INSIDE_INSERTED_UNCONTAINED = 9
    DELETION_OF_INSERTED = 10
    OUT_OF_SEQUENCE = 11


